### ISSUE TITLE
Low-resolution image on Welcome page

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#2]
Big Jotunheimen Places logo looks unsharp on Android. Probably due to lowres image or bad image type.

**Comment by designrad** [comment]
Hi-res exports from Sketch, 1x, 2x, 3x sizes:
https://github.com/designrad/Jotunheimen-tracking/tree/master/visual-design

**Comment by designrad** [comment]
![jotunheimen-logo](https://user-images.githubusercontent.com/23334059/27386834-498b44f6-5697-11e7-886d-c03245c6a03e.png)
![jotunheimen-logo 2x](https://user-images.githubusercontent.com/23334059/27386835-498c117e-5697-11e7-8dd6-76e2a8616fba.png)
![jotunheimen-logo 3x](https://user-images.githubusercontent.com/23334059/27386836-4991a648-5697-11e7-9b47-100e6c7556c5.png)

**Comment by prageer** [comment]
Please review this.

**Comment by designrad** [comment]
Thanks, I will review when new version available. Current apk "APK and Feedback #15" still has low-quality or distorted logo png.

**Comment by designrad** [comment]
iOS, Android OK. Closing issue.
