### ISSUE TITLE
Excel export: wrong number format for Lat, Long

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#30]
Lat, long values come out as nnn.nnn.nnn.nnnn, etc. Please fix so that they are in correct format, like 69.12345678, 18.87654321.

From Excel (same problem even if saved to .csv):
![image](https://user-images.githubusercontent.com/23334059/27386960-a8c1e9ca-5697-11e7-82d7-ed49d6acff97.png)

**Comment by prageer** [comment]
Please expand the columns in Excel

**Comment by designrad** [comment]
Expanding does not help. The value seems to be a number without the "."
<img width="867" alt="screenshot 2017-06-21 17 06 56" src="https://user-images.githubusercontent.com/23334059/27391342-0e49705e-56a4-11e7-8193-946cf159da86.png">

**Comment by prageer** [comment]
Could you give me it please?

**Comment by designrad** [comment]
Here's an export file from today:
https://www.dropbox.com/s/lrlagnfzyr0w2iz/downloadtracks-3.xls?dl=0

**Comment by designrad** [comment]
If you have trouble with Excel only, you can also save it as a .csv file, if this is easier for you. It should simple to import csv to Excel afterwards.

**Comment by designrad** [comment]
.csv or .txt files are also OK!

**Comment by designrad** [comment]
Seems the export file is actually a html file with xls extension. It's best if this is a simple txt file with "," or ";" or " " limit.

**Comment by designrad** [comment]
Verified OK as text file.
