### ISSUE TITLE
Critical: GPS is not updated during activity, only start position real.

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#31]
From newest Android apk: start position is taken from gps, but all saved points use the same start position. I tried even going to Google Maps and refresh position, but it didn't help. This must work. Please check this ASAP. Best, if position is always refreshed (even with a notification) when user selects "Like/Dislike".

**Comment by prageer** [comment]
Ok, Let me check carefully.

**Comment by prageer** [comment]
Hi, Niklas, IOS is ok, but android... still problem exists.
Let me keep trying...

**Comment by designrad** [comment]
Android tested and OK. iOS instll fails. Retrying.

**Comment by designrad** [comment]
Works on Android, iOS 29.6.2017 15:28
