### ISSUE TITLE
(Android) Expand timeout form 10sec to 30sec for "Getting Location"

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#37]
Client says many older androids have a 30sec-long gps activation process. Therefore they want to have a longer timeout than the current 10(?) seconds.

Also, change the "Getting Location" to "Activating GPS, max 30 sec"

**Comment by prageer** [comment]
Committed.
Please review. :)

**Comment by designrad** [comment]
Checked!
