### ISSUE TITLE
Like/Dislike page: Timestamp missing "zero" if minutes are 00, 10, 20, 30, 40, 50

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#38]
The timestamp in log is missing last zero is the minutes are 00, 10, 20, 30, 40, 50.

See the first timestamp: 19:1_
![img_4581](https://user-images.githubusercontent.com/23334059/27754226-c2bc71ca-5de9-11e7-8b51-6df82603cb7c.PNG)

**Comment by prageer** [comment]
![untitled](https://user-images.githubusercontent.com/28398785/27764726-66eb0c24-5ea9-11e7-91f7-4ec46f3695ce.png)
That is not the problem.
If "minutes" is less than 10, 0 will not appear.
Anyway, if it is less than 10, a leading zero is displayed.

**Comment by designrad** [comment]
OK
