### ISSUE TITLE
Let user fill in end-questionnaire even without gps location.

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#40]
Comment from client 5mins ago: "Good morning! I am trying the version you sent me yesterday, and I have a small problem to finish the tracking. When I try to end the trip and go to the questionnaire it asks for a GPS location, which it does not find, so therefore I can't go to the survey. Would it be possible to continue to the questionnaire eventhough it does not reach GPS signal?"

**Comment by designrad** [comment]
Audrius, there will be small bug fixes and changes during this and next week when the client is testing the app in Jotunheimen.

**Comment by prageer** [comment]
Hi, Nicklas. Committed.

**Comment by prageer** [comment]
Ok, Let me know during testing with client.

**Comment by designrad** [comment]
Checked
