### ISSUE TITLE
Latest app crashes when created signed apk

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#41]
I made a signed apk from current github, in Android Studio. Build > Generate signed APK. Uploaded to www.jotunheimen-tracking.no, and installed OK. App starts but crashes before splash or index screen.

**Comment by designrad** [comment]
06/07/2017
17.18	Gradle sync started

17.18	Gradle sync failed: Failed to find Build Tools revision 25.0.2
			Consult IDE log for more details (Help | Show Log)

17.18	Unregistered VCS root detected
			The directory /Users/niklas/projects/jotun-6-7-2017/Jotunheimen-tracking is under Git, but is not registered in the Settings.
			Add root  Configure  Ignore

17.18	Gradle sync started

17.18	Gradle sync failed: Failed to find Build Tools revision 25.0.2
			Consult IDE log for more details (Help | Show Log)

17.19	Gradle sync started

17.19	Gradle sync completed

17.19	Executing tasks: [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :react-native-device-info:generateDebugSources, :react-native-device-info:generateDebugAndroidTestSources, :react-native-device-info:mockableAndroidJar, :react-native-device-info:prepareDebugUnitTestDependencies, :RNLocation:generateDebugSources, :RNLocation:mockableAndroidJar, :RNLocation:prepareDebugUnitTestDependencies, :RNLocation:generateDebugAndroidTestSources]

17.20	Gradle build finished in 13s 626ms

17.20	Instant Run requires Android Gradle Plugin version 2.3.0-beta1. Update.
			(Don't show again)

17.20	Executing tasks: [:app:assembleDebug]

17.21	Gradle build finished in 38s 2ms

17.32	Executing tasks: [:app:assembleDebug, :react-native-device-info:assembleDebug, :RNLocation:assembleDebug]

17.32	Gradle build finished in 4s 651ms

17.32	Build APK
			APK(s) generated successfully.
			Reveal in Finder

17.43	Executing tasks: [:app:assembleRelease]

17.43	Gradle build finished in 9s 806ms

17.43	Generate Signed APK
			APK(s) generated successfully.
			Reveal in Finder

**Comment by prageer** [comment]
Well, I am not using Android studio. As i wrote in Doc, I make a signed apk in Terminal.

**Comment by prageer** [comment]
Please refer to this page.
https://facebook.github.io/react-native/docs/signed-apk-android.html#content

**Comment by designrad** [comment]
OK, Thanks!

**Comment by designrad** [comment]
This is the error from terminal:

13:04:14.607 [ERROR] [org.gradle.BuildExceptionReporter] 
13:04:14.607 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:04:14.608 [ERROR] [org.gradle.BuildExceptionReporter] 
13:04:14.608 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
13:04:14.608 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/niklas/projects/jotun-6-7-2017/Jotunheimen-tracking/JotunheimenPlaces/node_modules/react-native-gps/build.gradle' line: 1
13:04:14.608 [ERROR] [org.gradle.BuildExceptionReporter] 
13:04:14.609 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
13:04:14.609 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating project ':RNLocation'.
13:04:14.609 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0
13:04:14.609 [ERROR] [org.gradle.BuildExceptionReporter] 
13:04:14.610 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
13:04:14.610 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
13:04:14.610 [LIFECYCLE] [org.gradle.BuildResultLogger] 
13:04:14.611 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
13:04:14.611 [LIFECYCLE] [org.gradle.BuildResultLogger] 
13:04:14.611 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 3.111 secs
13:04:14.615 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 1, cache instances: 1, modules served from cache: 0, artifacts: 0
13:04:14.615 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (/Users/niklas/.gradle/caches/2.14.1/generated-gradle-jars) was closed 0 times.
13:04:14.616 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/Users/niklas/.gradle/caches/modules-2/metadata-2.16/module-metadata.bin)
13:04:14.617 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/Users/niklas/.gradle/caches/modules-2/metadata-2.16/artifact-at-repository.bin)
13:04:14.617 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/Users/niklas/.gradle/caches/modules-2).
13:04:14.618 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
13:04:14.619 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
13:04:14.620 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.001 secs
13:04:14.620 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/Users/niklas/.gradle/caches/2.14.1/plugin-resolution) was closed 0 times.
macbook:android niklas$

**Comment by designrad** [comment]
If you can, please create also new apk, so I can send to client asap.

**Comment by designrad** [comment]
Also, I noticed that when cloned from github, gradlew has 644 rights, so I need to change that to 755 manually. Maybe a strange github/osx file system issue. But wanted to let you know.

**Comment by prageer** [comment]
Yup. Committed new apk.

**Comment by designrad** [comment]
Thanks!
 Here's my gradlew, if that's the issue:macbook:android niklas$ ./gradlew --version

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Mac OS X 10.12.5 x86_64

macbook:android niklas$

**Comment by prageer** [comment]
i'll think about it.

Actually, I develop Android on windows com, and iOS on mac com.
so far, I did not make android apk on mac.
android was developed on windows.
Of course this is not fundamental.

maybe we need to review the development environment on Mac for android.

**Comment by designrad** [comment]
OK, I can also try on windows virtual machine. But for now, client is happy that the app is working. I also promised the app to be launched by Mon on Google Play.

**Comment by designrad** [comment]
Error from windows cmd: A problem occurred configuring project RNLocation:

<img width="673" alt="screenshot 2017-07-08 22 44 14" src="https://user-images.githubusercontent.com/23334059/27988975-fd6390c4-642e-11e7-90ff-b59792e60e5b.png">

**Comment by prageer** [comment]
Try this once.
Create a new project and create a signed apk once.

I wonder if there is an error there.

Obviously I make signed apk with gradlew assembleRelease directive.

**Comment by designrad** [comment]
From Android Studio, new project, then in terminal ./gradlew assembleRelease:
FAILED:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/niklas/projects/jotun-8-8-2017/Jotunheimen-tracking/JotunheimenPlaces/MyApplication/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.585 secs
macbook:MyApplication niklas$ 

Now I'll update gradle, Android Studio says I have 2.3.3, and newest is 3.3.
Then I'll try again, and also try directly from terminal `react-native init`

**Comment by designrad** [comment]
- OSX: Updated to java 1.8 from 1.7.
- Android Studio: sync issue: The SDK Build tools rev 23.0.1 us too low for project RNLocation. Minimum required is 25.0.0. Updated Build Tools and sync project.
=> Generated Signed APK from Android Studio > Got file, but crashes when started on phone.
=> Tried gradlew assembleRelease, now it runs OK, but still the package crashes when installed.

Screensharing? Or can you contact me on Upwork so that you can sign the apk with project keys? Thanks!

**Comment by prageer** [comment]
Hi, Nicklas. I'm sorry I can not help you much. It's a little hard to figure out why.
Please send me your key and password, i'll make the signed apk.
Thanks.

**Comment by designrad** [comment]
It's live now but with wrong image on welcome page. Not big issue. If you could create once again apk for release, I've updated the graphic, same size/name. Just check it says Jotunheimen Tracking under logo on welcome page. I'll then update Play Store.

**Comment by designrad** [comment]
I'll try again later and ask for some outside help. I'm still wondering why this is an issue on my machine.
