### ISSUE TITLE
Change apk version code from 1 to 1.1 or similar

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#42]
Hi Audrius, thanks for creating the apk to fast. Please change the version code from 1 to 1.1 or 2 for example. I'm not sure how to mark the version. Uploading your apk gives this error:
<img width="565" alt="screenshot 2017-07-12 11 55 51" src="https://user-images.githubusercontent.com/23334059/28112438-4cafe052-66f9-11e7-9c55-98f7ec0478a5.png">

**Comment by prageer** [comment]
Committed new apk 1.1.
Please try it.
Thanks.

**Comment by designrad** [comment]
Excellent, app is live.
