### ISSUE TITLE
Typing mistake and sending data 

### ISSUE THREAD

**Issue by LorenaUiT** [designrad/Jotunheimen-tracking#43]
Hi,
I have tried the last version of the app and I found a couple of issues that I would like to bring up. The first one is two typo errors: one is on the screen after you press "Start Activity", in the description it says joggin and it should be "jogging", and the other one is when you press "I like this area" it comes a list and the second option should be "Biological diversity".
The second issue is about sending data once the trip and the questionnaire are finished. I have seen that the data is not sent until you get internet connection and open the app. If the app is in the background, data is not sent (even if the phone has internet connection). Is it possible that the app sends the data when the phone is connected to internet? Or maybe that it sends a reminder so people open the app and then the data is sent?
Thanks for your help,
Best,
Lorena 
@prageer 
@designrad

**Comment by designrad** [comment]
Jogging typo corrected. Audrius, please comment on the GPS issue, if there's something that can be done. Otherwise please create new apk, 1.2.

**Comment by prageer** [comment]
Hi, Nicklas. Let me think... I will try to find a way.

**Comment by prageer** [comment]
and committed the apk 1.2

**Comment by designrad** [comment]
Deployed.
