### ISSUE TITLE
Move demograhics questionnaire to before survey questions

### ISSUE THREAD

**Issue by designrad** [designrad/Jotunheimen-tracking#46]
Hi Audrius,
Are you available for some extra work? Apple won't accept the app as such, and we need to change the demographics (age, income, etc) from the start of the app to the end part of the app.

So, the main flow would be:
1. Welcome
2. Consent
3. Instructions
--
4. Tracking, and finish tracking
5. Demographics (This is moved from start!)
6. Final questionnaire

And as with older version, Demographics is filled only once per app install. When are you able to do this change? And possibly only do it for iOS, Android is fine.

**Comment by prageer** [comment]
Hi, Committed 'src' forlder for ios app. You can use the folder instead of 'src' for ios app.

**Comment by designrad** [comment]
Checking.

**Comment by designrad** [comment]
Works OK, sent to App Store for approval. Thanks!
